---
language: go

go:
  - 1.7

go_import_path: github.com/FidelityInternational/diego-capacity-monitor

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y redis-server
  - go get github.com/pierrre/gotestcover
  - go get golang.org/x/tools/cover

script:
  - gotestcover -coverprofile=coverage.txt -race -covermode=atomic -v $(go list ./... | grep -v '/vendor/')

after_success:
  - bash <(curl -s https://codecov.io/bash)
